(() => {
let posts=[], filter='전체', limit=5, password='';
const $=s=>document.querySelector(s), dialog=$('#news-dialog'), content=$('#dialog-content');
const apiBase=location.hostname.endsWith('.github.io')?'https://bluet-golf-homepage.iamjssong.chatgpt.site':'';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,data){const response=await fetch(apiBase+path,data?{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+password},body:JSON.stringify(data)}:{cache:'no-store'});let result;try{result=await response.json()}catch{throw Error('게시판 서버에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.')}if(!response.ok)throw Error(result.error);return result}
function render(){const list=posts.filter(p=>filter==='전체'||p.category===filter);$('#news-status').textContent=list.length?'':filter==='전체'?'아직 등록된 소식이 없습니다. BlueT Golf의 새로운 이야기를 이곳에서 전하겠습니다.':`등록된 ${filter}가 없습니다.`;$('#news-list').innerHTML=list.slice(0,limit).map(p=>`<button class="news-row" data-post="${p.id}"><span class="news-category">${p.category}</span><span class="news-post-title">${escape(p.title)}</span><time>${escape(p.date)}</time><span aria-hidden="true">↗</span></button>`).join('');$('#more-news').hidden=list.length<=limit;$('#admin-dashboard').hidden=!password;$('#admin-login').hidden=!!password;$('#admin-button').hidden=!password;$('#write-post').hidden=!password;}
async function load(){try{posts=await api('/api/news');render()}catch(e){$('#news-status').textContent=e.message;$('#news-list').innerHTML='<button class="text-button" id="retry-news">다시 시도</button>';$('#retry-news').onclick=load}}
function show(html){content.innerHTML=html;if(!dialog.open)dialog.showModal()}
function detail(id){const p=posts.find(p=>p.id===id);show(`<p class="eyebrow">${p.category} · ${escape(p.date)}</p><h2 id="dialog-title">${escape(p.title)}</h2><div class="post-body">${escape(p.body)}</div>${password?'<div class="editor-actions"><button id="edit-post" class="small-button">수정</button><button id="delete-post" class="text-button">삭제</button></div>':''}`);if(password){$('#edit-post').onclick=()=>editor(p);$('#delete-post').onclick=()=>{show('<h2 id="dialog-title">이 글을 삭제할까요?</h2><p>삭제한 글은 복구할 수 없습니다.</p><div class="editor-actions"><button id="confirm-delete" class="small-button">삭제하기</button><button id="cancel-delete" class="text-button">취소</button></div><p id="form-error" role="alert"></p>');$('#cancel-delete').onclick=()=>detail(id);$('#confirm-delete').onclick=async()=>{try{await api('/api/delete',{id});dialog.close();await load()}catch(e){$('#form-error').textContent=e.message}}}}}
function editor(p={}){show(`<h2 id="dialog-title">${p.id?'소식 수정':'새 소식 작성'}</h2><form id="post-form"><label>분류<select name="category"><option${p.category==='공지'?' selected':''}>공지</option><option${p.category==='뉴스'?' selected':''}>뉴스</option></select></label><label>제목<input name="title" maxlength="100" required value="${escape(p.title||'')}" placeholder="제목을 입력해 주세요"></label><label>내용<textarea name="body" rows="9" maxlength="20000" required placeholder="전하고 싶은 소식을 작성해 주세요">${escape(p.body||'')}</textarea></label><p id="form-error" role="alert"></p><button class="small-button" type="submit">${p.id?'변경사항 저장':'게시하기'}</button></form>`);$('#post-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api('/api/news',{...Object.fromEntries(new FormData(e.target)),id:p.id});dialog.close();await load()}catch(err){$('#form-error').textContent=err.message}finally{button.disabled=false}}}
$('#admin-button').onclick=()=>{password='';posts=[];dialog.close();render();$('#login-form').reset();};
$('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#login-error').textContent='';password=String(new FormData(e.target).get('password')||'');try{await api('/api/login',{});e.target.reset();await load()}catch(err){password='';$('#login-error').textContent=err.message}finally{button.disabled=false}};
$('#write-post').onclick=()=>editor();$('#news-list').onclick=e=>{const button=e.target.closest('[data-post]');if(button)detail(Number(button.dataset.post))};document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;limit=5;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))});render()});$('#more-news').onclick=()=>{limit+=5;render()};$('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});render();
})();
